import { HealingSkill } from '../models/all-models';

export const HEALING_SKILLS: HealingSkill[] = [
  {
    id: 1,
    name: 'Dia',
    description: 'Small Healing to One member',
    cost: 8,
    diceRollLevel: 8,
    healingPercent: 25,
  },
  {
    id: 2,
    name: 'Diarama',
    description: 'Medium Healing to One member',
    cost: 15,
    diceRollLevel: 10,
    healingPercent: 45,
  },
  {
    id: 3,
    name: 'Diarahan',
    description: 'Full Healing to One member',
    cost: 25,
    diceRollLevel: 12,
    healingPercent: 100,
  },
  {
    id: 4,
    name: 'Media',
    description: 'Small Healing to All members',
    cost: 10,
    healingPercent: 25,
    diceRollLevel: 8,
    isForAllMembers: true,
  },
  {
    id: 5,
    name: 'Mediarama',
    description: 'Medium Healing to All members',
    cost: 25,
    healingPercent: 45,
    diceRollLevel: 10,
    isForAllMembers: true,
  },
  {
    id: 6,
    name: 'Mediarahan',
    description: 'Full Healing to All members',
    cost: 50,
    healingPercent: 100,
    diceRollLevel: 16,
    isForAllMembers: true,
  },
  {
    id: 7,
    name: 'Salvation',
    description: 'Full Healing to All members and clears status effects',
    cost: 60,
    diceRollLevel: 24,
    healingPercent: 100,
    isForAllMembers: true,
  },
];
